"""
``ReportService`` -- orchestrates a single ``POST /report`` request end-to-end.

Per the approved Phase 8 design, this composes ``ChatService`` rather than
duplicating session/memory/graph orchestration: a report request is built
into a ``ChatRequest(mode=ChatMode.REPORT, ...)`` and handed to
``ChatService.send_message()``, exactly matching ``schemas.chat``'s own
module docstring describing ``POST /report`` as "a thin convenience
wrapper that issues the same underlying request with ``mode='report'``".
Everything downstream of that -- assembling a ``ReportDocument`` from the
resulting Markdown, exporting it to a concrete file format, and persisting
the result -- is this file's own responsibility.

Two-tier failure handling (approved before implementation began):

* Research-pipeline failures -- anything ``ChatService.send_message()``
  raises (``SessionNotFoundError``, ``GraphExecutionError``,
  ``MaxRetriesExceededError``, ...) -- are never caught here. They
  propagate unchanged out of ``generate_report()``, exactly like
  ``/chat``'s identical failures do, and no ``Report`` row is ever created
  for them (there's nothing yet to attach one to).
* Export-step failures -- either the exporter itself
  (``ReportExportError``, covering both ``ReportTemplateError`` and
  ``ReportRenderingError``) or the subsequent disk write
  (``OSError`` -- disk full, permission denied, ...) -- are caught,
  produce a persisted ``Report`` row with ``status=FAILED`` plus the
  error, and are returned as a normal (if unhappy)
  ``ReportGenerationResponse``, not raised as an HTTP error. An ``OSError``
  is wrapped into a ``ReportRenderingError`` before being handled
  identically to an exporter failure -- from the caller's perspective,
  "the export step didn't produce a downloadable file" is one outcome
  regardless of which of the two actually failed.

``Report`` persistence happens exactly once, after the final outcome
(``COMPLETED`` or ``FAILED``) is already known -- no intermediate
``QUEUED``/``GENERATING`` row. Those two statuses exist on
``ReportGenerationStatus`` for a future asynchronous/queued
implementation (see that enum's own docstring); this synchronous
implementation never returns them, which is documented scope, not a gap.

``get_download()`` (backing ``GET /report/{id}/download``) returns a
plain ``ReportDownload`` dataclass, never the ``Report`` ORM row itself --
keeping the same "services return plain data, never persistence-layer
objects" boundary ``ChatService`` already establishes (it returns
``ChatResponse``, never a ``ConversationTurn`` row). It distinguishes two
different failure meanings, both mapped through exceptions that already
exist rather than new ones:

* The report id itself doesn't exist -- ``ReportRepository.require_by_id()``
  raises ``RecordNotFoundError`` (already maps to 404), propagated
  unchanged. Not caught or re-wrapped here.
* The report exists but has nothing downloadable -- ``status !=
  COMPLETED`` (e.g. a ``FAILED`` report), a missing ``file_path``, or
  (the one genuinely defensive case: the DB row claims a file exists but
  it's gone from disk, e.g. removed out-of-band) the referenced file not
  actually being present -- raises ``ResourceNotFoundError`` (also 404,
  but a semantically distinct case: the identifier was valid, the
  *download* isn't available). Each of the three raises with a message
  naming specifically why, so a client/log reader can't mistake this for
  "that report id was never valid."

Local-filesystem storage only -- ``file_path`` is read directly off the
``Report`` row and opened from local disk. No storage abstraction (object
storage, retention/cleanup policy, presigned URLs) is introduced here;
that would be solving a problem this project doesn't have yet (see
``ReportSettings.output_dir``'s own single-directory design), not a gap
in this file's scope.

Two independent ``database.session()`` units of work happen per request --
none held open across ``ChatService.send_message()`` (real LLM/retrieval/
search work) or the exporter/filesystem step -- mirroring the exact
reasoning ``ChatService`` itself already documents for the same problem.
The first unit of work is entirely inside ``ChatService`` (this file
doesn't open one of its own for it); the second is this file's own single
``Report``-row write, after the outcome is known.

Every identifier this file generates (``report_id``) follows the same
``f"{prefix}-{uuid4().hex[:8]}"`` convention ``ChatService`` already
established for ``session_id``/``message_id``/citation and execution-step
ids -- generated by the service layer, not the repository (no repository
in this codebase generates its own primary keys; see
``ConversationRepository.create_session()``, which takes an
already-generated id as a parameter).
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Dict
from uuid import uuid4

from app.core.config import ReportExportFormat as ConfigReportExportFormat
from app.core.config import Settings
from app.core.exceptions import ReportExportError, ReportRenderingError, ResearchMindError, ResourceNotFoundError
from app.core.interfaces.report_exporter import ReportDocument, ReportExporter
from app.core.logging import get_logger
from app.database.repositories.report_repository import ReportRepository
from app.database.session import Database
from app.models.enums import ReportExportFormat as ModelReportExportFormat
from app.models.enums import ReportGenerationStatus as ModelReportGenerationStatus
from app.models.report import Report as ReportRow
from app.reports.builder import build_report_document
from app.schemas.chat import ChatMode, ChatRequest
from app.schemas.common import ErrorBody, TokenUsage
from app.schemas.report import ReportExportFormat as SchemaReportExportFormat
from app.schemas.report import ReportGenerationRequest, ReportGenerationResponse
from app.schemas.report import ReportGenerationStatus as SchemaReportGenerationStatus
from app.services.chat_service import ChatService
from app.utils.time import utc_now

logger = get_logger(__name__)

# Matches Report.title's `String(300)` column width (app/models/report.py).
# A resolved title (conversation_title, or the query as a fallback) must
# never exceed this before reaching the ORM row -- ChatRequest.query alone
# allows up to 4000 characters, well past what the column can hold.
_TITLE_MAX_LENGTH = 300


@dataclass(frozen=True)
class ReportDownload:
    """
    Plain data returned by ``ReportService.get_download()`` -- deliberately
    not the ``Report`` ORM row itself (see this module's own docstring for
    why). Everything ``GET /report/{id}/download`` needs to stream a
    ``FileResponse`` and nothing else.
    """

    file_path: str
    mime_type: str
    filename: str


class ReportService:
    """
    Orchestrates a single ``POST /report`` request: run the underlying
    chat/research request in report mode, assemble a ``ReportDocument``,
    export it to the requested format, and persist the outcome.

    Constructed once at application startup, mirroring every other
    service in this codebase. ``report_exporters`` is an already-built
    ``{format: exporter}`` mapping (both concrete exporters are stateless
    singletons), not a callable into ``app.core.dependencies`` -- this
    module never imports that package, matching every other service's
    one-way dependency on the DI container (the container depends on
    services, never the reverse).
    """

    def __init__(
        self,
        *,
        database: Database,
        chat_service: ChatService,
        report_exporters: Dict[ConfigReportExportFormat, ReportExporter],
        settings: Settings,
    ) -> None:
        self._database = database
        self._chat_service = chat_service
        self._report_exporters = report_exporters
        self._settings = settings

    async def generate_report(self, request: ReportGenerationRequest) -> ReportGenerationResponse:
        """Run one full ``/report`` request and return its response."""
        requested_at = utc_now()

        # No try/except around this call: any ResearchMindError raised by
        # the underlying chat/research pipeline propagates unchanged, per
        # this module's own docstring on the two-tier failure design.
        chat_response = await self._chat_service.send_message(
            ChatRequest(
                query=request.query,
                session_id=request.session_id,
                mode=ChatMode.REPORT,
                stream=False,
                retrieval_options=request.retrieval_options,
                conversation_title=request.conversation_title,
            ),
            include_trace=False,
        )

        report_id = f"rpt-{uuid4().hex[:8]}"
        title = (chat_response.conversation_title or request.query).strip()[:_TITLE_MAX_LENGTH]

        document = build_report_document(
            title=title,
            session_id=chat_response.session_id,
            markdown=chat_response.answer,
            citations=chat_response.citations,
            metadata={"query": request.query, "message_id": chat_response.message_id},
        )

        exporter = self._report_exporters[ConfigReportExportFormat(request.export_format.value)]

        try:
            export_result = await exporter.export(document)
            output_path = Path(self._settings.report.output_dir) / export_result.filename
            await asyncio.to_thread(output_path.write_bytes, export_result.content)
        except (ReportExportError, OSError) as exc:
            translated = (
                exc
                if isinstance(exc, ReportExportError)
                else ReportRenderingError.wrap(
                    exc, f"Failed to write exported report file to disk for report {report_id!r}."
                )
            )
            return await self._handle_export_failure(
                report_id=report_id,
                session_id=chat_response.session_id,
                title=title,
                export_format=request.export_format,
                error=translated,
                requested_at=requested_at,
            )

        return await self._handle_export_success(
            report_id=report_id,
            document=document,
            export_format=request.export_format,
            file_path=output_path,
            file_size_bytes=len(export_result.content),
            mime_type=export_result.mime_type,
            token_usage=chat_response.research_metadata.token_usage,
            requested_at=requested_at,
        )

    async def get_download(self, report_id: str) -> ReportDownload:
        """
        Resolve the downloadable file for an already-generated report.

        See this module's own docstring for the two-tier "id doesn't
        exist" vs. "id exists but isn't downloadable" distinction --
        every raise site below names specifically which of the three
        "not downloadable" reasons applies, so a caller (and the client-
        facing error message) never mistakes an unavailable-but-valid
        report id for an invalid one.
        """
        async with self._database.session() as session:
            # require_by_id() raises RecordNotFoundError (already maps to
            # 404) if report_id doesn't exist at all -- propagated
            # unchanged, no handling needed here.
            row = await ReportRepository(session).require_by_id(report_id)

        if row.status != ModelReportGenerationStatus.COMPLETED:
            raise ResourceNotFoundError(
                f"Report {report_id!r} is not available for download: generation status is "
                f"{row.status.value!r}, not completed."
            )
        if row.file_path is None:
            raise ResourceNotFoundError(
                f"Report {report_id!r} has no exported file on record, even though it is marked completed."
            )
        if not await asyncio.to_thread(Path(row.file_path).is_file):
            raise ResourceNotFoundError(
                f"The exported file for report {report_id!r} no longer exists on disk (it may have been "
                "moved or deleted outside of the application)."
            )

        return ReportDownload(
            file_path=row.file_path,
            # Always set alongside file_path on the COMPLETED path (see
            # _handle_export_success) -- the fallback below only guards
            # against a row written by some other, not-yet-existing path
            # that set file_path without mime_type, rather than trusting
            # that invariant blindly.
            mime_type=row.mime_type or "application/octet-stream",
            filename=Path(row.file_path).name,
        )

    async def _handle_export_failure(
        self,
        *,
        report_id: str,
        session_id: str,
        title: str,
        export_format: SchemaReportExportFormat,
        error: ResearchMindError,
        requested_at: datetime,
    ) -> ReportGenerationResponse:
        generation_latency_ms = (utc_now() - requested_at).total_seconds() * 1000.0
        logger.warning(
            "Report export failed",
            extra={
                "report_id": report_id,
                "session_id": session_id,
                "export_format": export_format.value,
                "error_code": error.error_code,
            },
        )

        row = ReportRow(
            id=report_id,
            session_id=session_id,
            title=title,
            status=ModelReportGenerationStatus.FAILED,
            export_format=ModelReportExportFormat(export_format.value),
            generation_latency_ms=generation_latency_ms,
            error_code=error.error_code,
            error_message=error.message,
        )
        async with self._database.session() as session:
            await ReportRepository(session).add(row)

        return ReportGenerationResponse(
            report_id=report_id,
            session_id=session_id,
            status=SchemaReportGenerationStatus.FAILED,
            export_format=export_format,
            error=ErrorBody(
                error_code=error.error_code,
                message=error.message,
                retryable=error.retryable,
                request_id=error.request_id,
                trace_id=error.trace_id,
            ),
            created_at=row.created_at,
        )

    async def _handle_export_success(
        self,
        *,
        report_id: str,
        document: ReportDocument,
        export_format: SchemaReportExportFormat,
        file_path: Path,
        file_size_bytes: int,
        mime_type: str,
        token_usage: TokenUsage,
        requested_at: datetime,
    ) -> ReportGenerationResponse:
        generation_latency_ms = (utc_now() - requested_at).total_seconds() * 1000.0

        row = ReportRow(
            id=report_id,
            session_id=document.session_id,
            title=document.title,
            status=ModelReportGenerationStatus.COMPLETED,
            export_format=ModelReportExportFormat(export_format.value),
            executive_summary=document.executive_summary,
            key_findings=document.key_findings,
            sections=[section.model_dump(mode="json") for section in document.sections],
            conclusion=document.conclusion,
            citations=[citation.model_dump(mode="json") for citation in document.citations],
            report_metadata=document.metadata,
            generated_at=document.generated_at,
            file_path=str(file_path),
            file_size_bytes=file_size_bytes,
            mime_type=mime_type,
            generation_latency_ms=generation_latency_ms,
            prompt_tokens=token_usage.prompt_tokens,
            completion_tokens=token_usage.completion_tokens,
            total_tokens=token_usage.total_tokens,
        )
        async with self._database.session() as session:
            await ReportRepository(session).add(row)

        logger.info(
            "Report generated",
            extra={
                "report_id": report_id,
                "session_id": document.session_id,
                "export_format": export_format.value,
                "file_size_bytes": file_size_bytes,
                "generation_latency_ms": round(generation_latency_ms, 2),
            },
        )

        return ReportGenerationResponse(
            report_id=report_id,
            session_id=document.session_id,
            status=SchemaReportGenerationStatus.COMPLETED,
            export_format=export_format,
            download_url=self._build_download_url(report_id),
            report=document,
            file_size_bytes=file_size_bytes,
            generation_latency_ms=generation_latency_ms,
            token_usage=token_usage,
            created_at=row.created_at,
        )

    def _build_download_url(self, report_id: str) -> str:
        """
        Centralized so the not-yet-built ``GET /report/{id}/download``
        route and this response stay in lockstep -- both derive the same
        path from ``settings.app.api_prefix`` rather than one of them
        hardcoding ``/api/v1`` separately.
        """
        return f"{self._settings.app.api_prefix}/report/{report_id}/download"
